"""Backend-neutral LLM request/response contracts for prompt-driven actions.

The module defines stable types for model requests, responses, and backend
implementations so prompt-driven action selection remains decoupled from the
underlying LLM provider.

Example:
    >>> req = LlmRequest(prompt=rendered_prompt, max_new_tokens=16)
    >>> resp = backend.complete(req)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .prompts import RenderedPrompt


@dataclass(frozen=True)
class LlmRequest:
    """Structured LLM request used by `LlmBackend` implementations.

    :param prompt: RenderedPrompt containing the text and action catalogue.
    :param max_new_tokens: Maximum number of tokens to generate.
    :param temperature: Sampling temperature; 0.0 implies deterministic sampling.
    :param stop_sequences: Tuple of strings that stop generation when emitted.
    """

    prompt: RenderedPrompt
    max_new_tokens: int = 32
    temperature: float = 0.0
    stop_sequences: tuple[str, ...] = ("</action>",)


@dataclass(frozen=True)
class LlmResponse:
    """Normalized LLM response returned by `LlmBackend.complete`.

    :param raw_text: Full text generated by the model.
    :param backend: Backend identifier (e.g., 'openai', 'tunix').
    :param model: Model name or revision string.
    :param latency_ms: Optional end-to-end latency in milliseconds.
    :param token_logprobs: Optional per-token log-probabilities.
    :param token_ids: Optional generated token ids.
    :param prompt_token_ids: Optional token ids corresponding to the prompt.
    """

    raw_text: str
    backend: str
    model: str
    latency_ms: float | None = None
    token_logprobs: tuple[float, ...] | None = None
    token_ids: tuple[int, ...] | None = None
    prompt_token_ids: tuple[int, ...] | None = None


class LlmBackend(Protocol):
    """Backend interface for synchronous LLM completion calls."""

    def complete(self, request: LlmRequest) -> LlmResponse:
        """Perform a synchronous completion request.

        :param request: LlmRequest describing prompt and decoding options.
        :returns: LlmResponse with generated text and optional metadata.
        """
        ...


@dataclass(frozen=True)
class ScriptedLlmBackend:
    """A trivial `LlmBackend` that returns a fixed scripted response.

    Useful in tests and examples where deterministic model output is required.
    """

    raw_text: str
    model: str = "scripted"

    def complete(self, request: LlmRequest) -> LlmResponse:
        """Return a deterministic scripted response, useful for tests.

        :param request: Ignored; present for interface compatibility.
        :returns: A LlmResponse with the scripted `raw_text` and zero latency.
        """
        return LlmResponse(self.raw_text, "scripted", self.model, 0.0)
